### ISSUE TITLE
Can timy output be made stored in a dictionary?

### ISSUE THREAD

**Issue by jcopps** [ramonsaraiva/timy#23]
@ramonsaraiva 
I would like to know if Timy output could be stored in a dictionary rather than printing on to the console or logging to a log file? 
Also, Can Timy be used in production code without any compromise in performance?

**Comment by jcopps** [comment]
@ramonsaraiva  Can you please comment on this.

**Comment by ramonsaraiva** [comment]
Hello @jcopps - if you want to, you can submit a PR implementing this functionality, I don't mind having a third option for storing the messages. I'm pretty sure you could be able to accomplish this by writing a custom log handler: https://docs.python.org/3/library/logging.handlers.html#

To the production code question, I don't think the package would hurt your performance, because all it does is `time.perf_counter` or `time.process_time` calls, besides the log ones.

**Comment by jcopps** [comment]
@ramonsaraiva  I will try to give a PR by this weekend. 
Since this has got decorators support, will this work fine on a multi threaded application if I store the time stats in an isolated store?

**Comment by ramonsaraiva** [comment]
I'm not sure. It will depend on how you will use this `store`.. You'll need to give me an example so I can understand the scope.
