### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by dmtucker** [ramonsaraiva/timy#4]
You should move code out of `__init__.py`. That should usually be left empty.
Also, are you aware of the [`timeit`](https://docs.python.org/3/library/timeit.html) module?

``` sh
$ python -m timeit -s 'foo = 5' -- 'foo + 1'
10000000 loops, best of 3: 0.044 usec per loop
```

**Comment by ramonsaraiva** [comment]
Yes, aware of timeit module, as described on readme.
Thanks for your feedback.

**Comment by SethMMorton** [comment]
@dmtucker The `timeit` example you showed has nothing to do with the intent of this module. Are you implying that `timy` and `timeit` serve the same purpose?  Because as far as I can tell `timeit` does not have any of the functionality that `timy` introduces (i.e. decorators and context mangers, etc.). What is the purpose of that feedback?

**Comment by SethMMorton** [comment]
@ramonsaraiva Along the same lines as my above comment, I am not sure that stating "you can also use the `timeit` module" in your README is accurate. I don't see much overlap of functionality of the two modules, except for the superficial "they both time things"; `timeit` focuses on timing arbitrary strings by interpreting as python code, whereas `timy` gives a convenient way to time functions and code blocks.

**Comment by ramonsaraiva** [comment]
@SethMMorton I'm really really happy with your comments cause you understood exactly what i wanted to bring with this module. The reason i mentioned `timeit` is cause i knew people would come saying that Python already has a built-in module that does time tracking. Although, `timy` is a little bit different since you can have more flexibility when measuring time. I created this module cause i felt in need of something like this, and i'm happy some people actually liked it and are supporting it.

I understand @dmtucker's point tho, he probably just wanted to make sure i know about `timeit` and what it does.

Thank you, @SethMMorton.

**Comment by SethMMorton** [comment]
@ramonsaraiva Then might I recommend that rather than just saying "you can also use the `timeit` module", you instead highlight how the intent of `timy` is different than `timeit`?  Hopefully that will prevent people from blindly asking if you have heard of `timeit` instead of taking the time to understand `timy`.

**Comment by ramonsaraiva** [comment]
Will change the README tomorrow with your suggestion, thank you again.

**Comment by dmtucker** [comment]
@ramonsaraiva Ah, sorry; I didn't catch the reference in the README. This seems like a cool idea.

@SethMMorton Doesn't hurt to ask... People of all levels of experience drop in to #python on Freenode (see #3).
